USE db_delivery;
CREATE TABLE users(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(180) NOT NULL UNIQUE,
name VARCHAR(90) NOT NULL,
lastName VARCHAR(90) NOT NULL,
phone VARCHAR(90) NOT NULL,
image VARCHAR(255) NULL,
password VARCHAR(90) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

